name = "nuxt-server-test"
main = ".output/server/index.mjs"
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".output/public"

[[d1_databases]]
binding = "DB"
database_name = "nuxt-server-test-db"
database_id = "1ba9f5e6-800f-404c-86ae-33812b7f03e8"
